-- Schema as previously generated by Hibernate (ddl-auto=update).
-- Databases created that way are baselined at this version and skip it
-- (spring.flyway.baseline-on-migrate=true).

create table users (
    id         bigint generated by default as identity primary key,
    name       varchar(255) not null,
    email      varchar(255) not null,
    password   varchar(255) not null,
    created_at timestamp(6) not null,
    constraint uk_users_email unique (email)
);

create table runs (
    id               bigint generated by default as identity primary key,
    distance_km      float(53)    not null,
    duration_minutes integer      not null,
    calories_burned  integer      not null,
    notes            varchar(500),
    user_id          bigint       not null,
    created_at       timestamp(6) not null,
    constraint fk_runs_user foreign key (user_id) references users (id)
);

create table books (
    id          bigint generated by default as identity primary key,
    title       varchar(255) not null,
    author      varchar(255) not null,
    description varchar(255) not null,
    user_id     bigint       not null,
    created_at  timestamp(6) not null,
    constraint fk_books_user foreign key (user_id) references users (id)
);

create table media (
    id          bigint generated by default as identity primary key,
    title       varchar(255) not null,
    type        varchar(255) not null,
    url         varchar(255) not null,
    description varchar(255) not null,
    user_id     bigint       not null,
    created_at  timestamp(6) not null,
    constraint fk_media_user foreign key (user_id) references users (id)
);
