-- Long-lived refresh tokens; only a SHA-256 hash of each token is stored.
-- A used (rotated) token is kept with revoked_at set until it expires, so a
-- second use can be detected as theft.
create table refresh_tokens (
    id         bigint generated by default as identity primary key,
    user_id    bigint       not null,
    token_hash varchar(64)  not null,
    expires_at timestamp(6) not null,
    revoked_at timestamp(6),
    created_at timestamp(6) not null,
    constraint uk_refresh_tokens_hash unique (token_hash),
    constraint fk_refresh_tokens_user foreign key (user_id) references users (id) on delete cascade
);

create index idx_refresh_tokens_user on refresh_tokens (user_id);
