-- Accounts must confirm their e-mail address. Existing accounts predate the
-- check and are treated as verified.
alter table users add column email_verified boolean default false not null;
update users set email_verified = true;

-- One-time codes sent by e-mail (verification, password reset). Only a bcrypt
-- hash is stored; a user has at most one active code per purpose.
create table email_codes (
    id         bigint generated by default as identity primary key,
    user_id    bigint       not null,
    purpose    varchar(30)  not null,
    code_hash  varchar(100) not null,
    attempts   integer      default 0 not null,
    expires_at timestamp(6) not null,
    created_at timestamp(6) not null,
    constraint uk_email_codes_user_purpose unique (user_id, purpose),
    constraint fk_email_codes_user foreign key (user_id) references users (id) on delete cascade
);
